"""Regenerate agent/tools/ptb/data/e3_registry.json from the curated KB.

Merges the restored agent/data/parameters.json (curated from the Optidrive E3
IP20 User Guide V1.05) into the .ptb parameter registry:

- Existing hand-checked entries are preserved verbatim; only their advisory
  min/max/name gaps are filled from the KB where the registry had null.
- New entries are added only when type and scale can be inferred safely:
    * units containing Hz, A or %  -> type R, scale 10 (documented Modbus
      scaling: freq x10, current x10, percent x10)
    * units V, RPM, kHz, mins, degC -> type R, scale 1
    * units s, ohm, mH             -> type R, scale from the number of
      decimals in the KB range strings (0.00 -> 100, 0.0 -> 10)
    * unitless integer ranges      -> type L, scale 1 (enumerated selects)
  Every inference rule reproduces all 33 hand-checked entries exactly.
- Ambiguous parameters are excluded and listed in todo.parameters_not_covered:
  blank or "see below" composite ranges (indexed suspects) and plain numeric
  access codes whose RParam/LParam element type cannot be determined.

Run from the repo root: .venv/bin/python scripts/generate_e3_registry.py
"""

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
KB_PARAMS = REPO_ROOT / "agent" / "data" / "parameters.json"
REGISTRY = REPO_ROOT / "agent" / "tools" / "ptb" / "data" / "e3_registry.json"

# Codes whose .ptb element type cannot be inferred safely.
EXCLUDE = {
    "P-14": "numeric access code; RParam/LParam type unconfirmed",
    "P-37": "numeric access code; RParam/LParam type unconfirmed",
    "P-32": "composite/indexed parameter; range blank in KB, addressing unconfirmed",
    "P-40": "composite/indexed parameter; range blank in KB, addressing unconfirmed",
}

NUMERIC_RE = re.compile(r"^-?\d+(\.\d+)?$")


def parse_number(text):
    """Return (value, decimals) for a plain numeric string, else (None, 0)."""
    if not isinstance(text, str):
        return None, 0
    text = text.strip()
    if not NUMERIC_RE.match(text):
        return None, 0
    decimals = len(text.split(".")[1]) if "." in text else 0
    return float(text), decimals


def infer_entry(param):
    """Return a registry entry dict for a KB parameter, or None if unsafe."""
    code = param["id"]
    rng = param.get("range") or {}
    units = (rng.get("units") or "").strip()
    min_v, min_d = parse_number(rng.get("min"))
    max_v, max_d = parse_number(rng.get("max"))
    _, def_d = parse_number(param.get("default"))
    decimals = max(min_d, max_d, def_d)

    if units in ("", "-") and max_v is None and min_v is None:
        return None  # blank/see-below range: indexed suspect, unsafe

    if "Hz" in units or units == "A" or units == "%":
        ptype, scale = "R", 10
    elif units in ("V", "RPM", "kHz", "mins", "degC", "°C"):
        ptype, scale = "R", 1
    elif units in ("s", "Ω", "ohm", "mH"):
        ptype, scale = "R", 10 ** decimals if decimals else 1
    elif units in ("", "-") and decimals == 0:
        ptype, scale = "L", 1  # enumerated select
    elif units in ("", "-") and decimals > 0:
        ptype, scale = "R", 10 ** decimals  # unitless real (e.g. PI gain)
    else:
        return None  # unrecognised units: unsafe

    group_num, param_num = derive(code)
    src = param.get("source") or {}
    return {
        "name": param["name"],
        "type": ptype,
        "scale": scale,
        "units": units if units not in ("", "-") else None,
        "min_display": min_v,
        "max_display": max_v,
        "group_num": group_num,
        "param_num": param_num,
        "indexed": False,
        "provenance": "inferred",
        "provenance_note": (
            "Generated by scripts/generate_e3_registry.py from the curated "
            f"data/parameters.json ({src.get('section', '?')}, "
            f"p.{src.get('page', '?')}). Type/scale inferred from units and "
            "range formatting per the documented Modbus scaling conventions."
        ),
    }


def derive(code):
    m = re.match(r"^P(\d{0,2})-(\d{1,2})$", code)
    group = int(m.group(1)) if m.group(1) else 1
    return group, int(m.group(2))


def main():
    kb = json.loads(KB_PARAMS.read_text(encoding="utf-8"))
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    existing = registry["parameters"]

    added, skipped = [], []
    for param in kb["parameters"]:
        code = param["id"]
        if code in EXCLUDE:
            skipped.append(f"{code} ({EXCLUDE[code]})")
            continue
        if code in existing:
            # Hand-checked entry stays authoritative; fill advisory gaps only.
            entry = existing[code]
            rng = param.get("range") or {}
            min_v, _ = parse_number(rng.get("min"))
            max_v, _ = parse_number(rng.get("max"))
            if entry.get("min_display") is None and min_v is not None:
                entry["min_display"] = min_v
            if entry.get("max_display") is None and max_v is not None:
                entry["max_display"] = max_v
            continue
        entry = infer_entry(param)
        if entry is None:
            skipped.append(f"{code} (range/units too ambiguous to infer)")
            continue
        existing[code] = entry
        added.append(code)

    registry["parameters"] = dict(
        sorted(existing.items(), key=lambda kv: derive(kv[0]))
    )
    settable = [c for c in registry["parameters"] if not c.startswith("P00")]
    kb_ids = {p["id"] for p in kb["parameters"]}
    registry["todo"] = {
        "missing_source": (
            "Resolved 2026-07-29: the curated data/parameters.json was "
            "restored and this registry regenerated from it via "
            "scripts/generate_e3_registry.py."
        ),
        "parameters_not_covered": sorted(
            kb_ids - set(settable), key=lambda c: derive(c)
        ),
        "parameters_not_covered_reasons": skipped,
        "read_only_not_covered": (
            "P00-xx beyond the six listed are intentionally omitted: the "
            "registry validates writes and read-only parameters are never "
            "written; diagnosis reads them from data/parameters.json."
        ),
        "next_steps": [
            "Confirm code->(group_num, param_num) addressing and scale "
            "factors against a .ptb saved from a real E3 drive.",
        ],
    }

    REGISTRY.write_text(
        json.dumps(registry, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"added {len(added)}: {', '.join(added)}")
    print(f"skipped {len(skipped)}:")
    for s in skipped:
        print(f"  {s}")
    print(f"total settable entries: {len(settable)}")


if __name__ == "__main__":
    main()
